### PR TITLE
Fix module path

### PR DESCRIPTION
**Pull request by SJaffa**
Finding where a module's files have been stored using `module.__file__` fails on some systems. Added an alternative method - `print(module)`. Works on Ubuntu 20.04 with Python 3.8.10, might need to check at least one of these works on other systems.

### CODE REVIEW

File: notebooks/050import.ipynb [hunk 1]
```diff
@@ -215,30 +215,60 @@
...
+   "cell_type": "markdown",
+   "metadata": {},
+   "source": [
+    "Some modules do not use the `__file__` attribute so you may get an error:\n",
+    "\n",
+    "``` python\n",
+    "AttributeError: module 'modulename' has no attribute '__file__'\n",
+    "```\n",
+    "\n",
+    "If this is the case `print(modulename)` should give the same infomation."
```
Comment (matt-graham) [inline notebooks/050import.ipynb:252]:
```suggestion
    "If this is the case `print(modulename)` should display a description of the module object which will include an indication if the module is a 'built-in' module written in C (in which case the file path will not be specified) or the file path to the module otherwise."
```

It might be worth clarifying here that the file path will probably still not be shown if accessing the `__file__` attribute failed, but that a more helpful description will be displayed including a specific indication that the module is built-in.

**Review by matt-graham — APPROVED** [review]
Looks good to me in general. I have made one suggestion of adding a bit of extra detail around what happens when running `print(modulename)` to avoid confusion when this also does not display an actual path to the module. I've tested running this on Python 3.8 on both Ubuntu 20.04 and Windows 10 (both in `conda` environments) and everything works as expected in both cases.
